server:
  port: 8090
spring:
  application:
    name: ORDER
  datasource:
    password: sa
    url: jdbc:postgresql://localhost:5432/order
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka